apiVersion: apps/v1
kind: Deployment
metadata:
  name: storemanageractors
  namespace: dapr-storemanager
  labels:
    app: storemanageractors
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storemanageractors
  template:
    metadata:
      labels:
        app: storemanageractors
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "storemanageractors"
        dapr.io/app-port: "6000"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: storemanageractors
        image: store-manager/actors:1.0
        ports:
        - containerPort: 6000


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: storemanageractors
  name: storemanageractors
  namespace: dapr-storemanager
spec:
  type: LoadBalancer
  ports:
  - name: "data"
    port: 6000
    targetPort: 6000
  selector:
    app: storemanageractors
