apiVersion: apps/v1
kind: Deployment
metadata:
  name: storemanagerorders
  namespace: dapr-storemanager
  labels:
    app: storemanagerorders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storemanagerorders
  template:
    metadata:
      labels:
        app: storemanagerorders
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "storemanagerorders"
        dapr.io/app-port: "6001"
        dapr.io/config: "dapr-config"
    spec:
      containers:
      - name: storemanagerorders
        image: store-manager/orders:1.0
        ports:
        - containerPort: 6001

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: storemanagerorders
  name: storemanagerorders
  namespace: dapr-storemanager
spec:
  type: LoadBalancer
  ports:
  - name: "data"
    port: 6001
    targetPort: 6001
  selector:
    app: storemanagerorders

